services:
  - type: web
    env: python
    envVars:
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: RUSTUP_HOME
        value: /tmp/rustup
    buildCommand: |
      mkdir -p /tmp/cargo /tmp/rustup
      pip install -r requirements.txt
