services:
  - type: web
    name: my-app
    runtime: python
    buildCommand: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
      pip install -r requirements.txt
    startCommand: gunicorn app:app
